name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIA5XYH2L5KFPEW2A6K
        aws-secret-access-key: 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
        aws-region: us-west-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 944372342612.dkr.ecr.us-west-2.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t 944372342612.dkr.ecr.us-west-2.amazonaws.com/myimage:latest -f Dockerfile .
        docker push 944372342612.dkr.ecr.us-west-2.amazonaws.com/myimage:latest

    - name: Deploy to EKS
      run: |
        aws eks --region us-west-2 update-kubeconfig --name ecrtest
        kubectl rollout restart deployment mypro
